pre-commit:
  parallel: true
  commands:
    lint:
      run: npm run lint
    format:
      run: npm run format
    sonar:
      run: npm run sonar
pre-push:
  parallel: true
  commands:
    lint:
      run: npm run lint
    format:
      run: npm run format
    sonar:
      run: npm run sonar
